### ISSUE TITLE
Please use names such as luarocks-5.1 if possible

### ISSUE THREAD

**Issue by hishamhm** [siffiejoe/prg-lr4win#1]
...for consistency with the Unix installer. Thanks!

**Comment by siffiejoe** [comment]
I don't know about that. I chose those names to be more consistent with how things are called on Windows (e.g. `lua5x.dll` not `lua5.x.dll` from the official "make mingw" target, `lua5x.exe` not `lua5.x.exe` from recent LuaBinaries). So it seems we get consistency issues either way ...

What about providing both options?

**Comment by hishamhm** [comment]
I was referring to the command lines for LuaRocks only.

It's really unfortunate that the Lua authors refuse to make a call on how to version their binaries and we ended up with this mess, but we _did_ make a call in LuaRocks, and we chose `luarocks-5.x`.

**Comment by siffiejoe** [comment]
> I was referring to the command lines for LuaRocks only.

I know. But I already have executables like `lua53.exe` and `luac53.exe` in this package, and I'm not sure what's worse: naming inconsistencies across different OSes or naming inconsistencies within a package.

**Comment by hishamhm** [comment]
Thank you!

**Comment by hishamhm** [comment]
Addendum: I understand your concern about naming inconsistency within the package, but the Lua naming issue exists for very long now, and I try hard to leave LuaRocks out of this mess. Thanks again for making the change!
